### ISSUE TITLE
Ice Abilities

### ISSUE THREAD

**Issue by adelthesuper** [TheMysticSword/AspectAbilities#10]
In recent update you double the radius and increase health of crystal that Glacial enemies drop. Can you put the radius back how it was or make a Config option for it? That new radius size is just tooo overpowered when there is multiple glacial enemies. The 30m was just fine but the 60m is insane and quite annoying to deal with.

**Comment by TheMysticSword** [comment]
Ice crystals will be slightly changed in the upcoming patch: instead of constantly stacking the debuff on you, they will send a frostbite shockwave every 10 seconds that inflicts the debuff for 12 seconds, which stacks if you get hit by a shockwave again. This should make the ability much more manageable for players since you will have time to get rid of the ice crystal before it debuffs you.
Please let me know if dealing with Glacial enemies feels better after this change.

**Comment by adelthesuper** [comment]
alright thanks

**Comment by adelthesuper** [comment]
yeah its still too op dude that radius is just tooo damn big. On monsoon your constantly hit by it, impossible to stop or avoid. You kill one 5-6 more show up.

**Comment by SalTheThief** [comment]
I agree, this effect is pretty ridiculous. Especially considering these mobs spawn on stage 1. If you make it so you get your HP back when the effect is over or if you purged the debuff when you kill the crystal I think it'd be fine.

**Comment by TheMysticSword** [comment]
Changed the effect to just lock skills for a short amount of time, and also made the mod fully configurable if you want to nerf it
